---
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
trigger: 
  - master
extends:
  template: ./templet/spring.yaml
  parameters:
    branch: 'master'
    goal: 'build'
    javaversion: '1.17'
