pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-22.04
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkversionOption: '1.17'
- task: SonarQubePreBuild@1
  inputs:
    projectKey: 'sohail_spring'
    projectName: 'sohail'
    projectVersion: '1.0'
- task: SonarQubePostTest@1