pool:
  name: 'Azure Pielines'
  VmImage: 'ubuntu-latest'
trigger:
- main
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: '3.9.4'
    jdkVersionOption: '1.17'
    


 