---

pool: 
 - vmImage: ubuntu-latest

trigger:
  - main
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'hema789/spring_project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'