pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-22.04
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkversionOption: '1.17'
    sonarQubeRunAnalysis: true
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SONAR_CLOUD'
    scannerMode: 'CLI'
    cliProjectKey: 'sohail'
    cliProjectName: 'sohail_spring'
    cliSources: 'src'

